In [1]:
import numpy as np

In [3]:
arr=np.array([[1,6012],
              [2,7079],
              [3,6886],
              [4,7230],
              [5,4598],
              [6,5564],
              [7,6971],
              [8,7763],
              [9,8032],
              [10,9569]])
print(arr)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [5]:
arr[:,1]+=10000
print(arr)

[[    1 26012]
 [    2 27079]
 [    3 26886]
 [    4 27230]
 [    5 24598]
 [    6 25564]
 [    7 26971]
 [    8 27763]
 [    9 28032]
 [   10 29569]]


In [6]:
arr[:,1]>7000


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
arr[arr[:,1]>7000]

array([[    1, 26012],
       [    2, 27079],
       [    3, 26886],
       [    4, 27230],
       [    5, 24598],
       [    6, 25564],
       [    7, 26971],
       [    8, 27763],
       [    9, 28032],
       [   10, 29569]])

In [8]:
np.sort(arr[:,1])

array([24598, 25564, 26012, 26886, 26971, 27079, 27230, 27763, 28032,
       29569])